### PR TITLE
add button with link to github repo

### PR DESCRIPTION
**Pull request by ackao**
button generated from https://buttons.github.io/

### CODE REVIEW

**Comment by ackao** [comment]
50/50 on whether i managed to put this in a reasonable place or not...

**Review by Juanaxu — COMMENTED** [review]
Someone's made this for Angular already:
https://github.com/scttcper/ngx-github-buttons

Can you use that?  I'd prefer to keep everything in the FE in the same framework if possible.  Installation instructions are in the repository and you should be able to stick the html in client/src/app/app.component.html in the nz-header, and any css you need in client/src/app/app.component.css

**Comment by ackao** [comment]
yep. my google search abilities failed me on this one. i'll switch it over.

**Comment by ackao** [comment]
switched to angular but i put it in the footer instead cuz it looked weird in the header

**Review by Juanaxu — APPROVED** [review]

**Pull request merged**
